### PR TITLE
Updated

### PR DESCRIPTION
**Pull request by meganz-meganz**
I'm hubred-rev...WE WILL CONTINUE STRUGGLE TO END.

### CODE REVIEW

**Comment by meganz-meganz** [comment]
**This is very sad. Because we can't freely read something by Chinese TTS.**

**Comment by meganz-meganz** [comment]
**This is sad for us. Because we can only train DEEP LEARNING MODEL for listening to them.
This is a FREE AI Voice change MODEL train DEEP LEARNING repository:
https://github.com/CorentinJ/Real-Time-Voice-Cloning
https://cloud.tencent.com/developer/article/1538852
This is a similar Chinese repository:
https://github.com/KuangDD/zhrtvc**

**Comment by ProletRevDicta** [comment]
感谢

**Comment by ProletRevDicta** [comment]
By the way, it seems better to translate 《社会主义政治经济学》 as “The Political Economy of Socialism“ ？

**Pull request merged**
